### PR TITLE
Implement 10K Genes submission bridge

### PR DESCRIPTION
**Pull request by kemitchell**
@juul, here is WIP on the 10K Genes to PDC bridge. I don't think you need to look into the code here, but thought you'd like to be aware.

How would you like to go about testing?

### CODE REVIEW

**Comment by kemitchell** [comment]
@Juul, should I go ahead and deploy to pdf.biobricks.org, so you can try it?

**Comment by Juul** [comment]
I had to tweak a few things. Should I make a pull request in your direction?

**Comment by kemitchell** [comment]
Sure.

**Comment by Juul** [comment]
Ah never mind I just pushed. It would be great if you could deploy the current version!

**Comment by kemitchell** [comment]
Deployed.

**Pull request merged**
